import CreateModal from "@/components/CreateModal";
import "./globals.css";
import ViewModal from "@/components/ViewModal";

export const metadata = {
  title: "Trello Clone",
  description: "Generated by SkaiLord",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
        <CreateModal />
        <ViewModal />
      </body>
    </html>
  );
}
